/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PrmButton {
        "customclass": string;
        "disabled": boolean;
        "loading": string;
        "name": string;
        "outline": boolean;
        "round": 'none' | 'sm' | 'md' | 'lg' | 'xl' | 'full';
        "size": 'xs' | 'sm' | 'md' | 'lg' | 'xl';
        "variant": 'primary' | 'secondary' | 'success' | 'warning' | 'danger' | 'info' | 'light' | 'dark';
    }
    interface PrmButtonGroup {
        "round": 'none' | 'sm' | 'md' | 'lg' | 'xl' | 'full';
    }
}
export interface PrmButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPrmButtonElement;
}
export interface PrmButtonGroupCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPrmButtonGroupElement;
}
declare global {
    interface HTMLPrmButtonElement extends Components.PrmButton, HTMLStencilElement {
    }
    var HTMLPrmButtonElement: {
        prototype: HTMLPrmButtonElement;
        new (): HTMLPrmButtonElement;
    };
    interface HTMLPrmButtonGroupElement extends Components.PrmButtonGroup, HTMLStencilElement {
    }
    var HTMLPrmButtonGroupElement: {
        prototype: HTMLPrmButtonGroupElement;
        new (): HTMLPrmButtonGroupElement;
    };
    interface HTMLElementTagNameMap {
        "prm-button": HTMLPrmButtonElement;
        "prm-button-group": HTMLPrmButtonGroupElement;
    }
}
declare namespace LocalJSX {
    interface PrmButton {
        "customclass"?: string;
        "disabled"?: boolean;
        "loading"?: string;
        "name"?: string;
        "onOnclick"?: (event: PrmButtonCustomEvent<MouseEvent>) => void;
        "outline"?: boolean;
        "round"?: 'none' | 'sm' | 'md' | 'lg' | 'xl' | 'full';
        "size"?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
        "variant"?: 'primary' | 'secondary' | 'success' | 'warning' | 'danger' | 'info' | 'light' | 'dark';
    }
    interface PrmButtonGroup {
        "onOnclick"?: (event: PrmButtonGroupCustomEvent<MouseEvent>) => void;
        "round"?: 'none' | 'sm' | 'md' | 'lg' | 'xl' | 'full';
    }
    interface IntrinsicElements {
        "prm-button": PrmButton;
        "prm-button-group": PrmButtonGroup;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "prm-button": LocalJSX.PrmButton & JSXBase.HTMLAttributes<HTMLPrmButtonElement>;
            "prm-button-group": LocalJSX.PrmButtonGroup & JSXBase.HTMLAttributes<HTMLPrmButtonGroupElement>;
        }
    }
}
